#  PYTHON CLASSES, *FIGURATIVELY*

<img src="https://images.unsplash.com/photo-1529693662653-9d480530a697?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGNsYXNzZXN8ZW58MHx8MHx8fDA%3D" width = 1500/>

<span style="color:grey">

"There are two structures: classes and functions.

When you pick the wrong structure,

your code will be harder to maintain, 

leading to bugs that potentially accidentally lead to shooting of rockets at other countries, 

leading to World War 3, 

and in the worst case one country creates a weapon that creates a super massive black hole 

that swallows the entire universe."

</span>

by [ArjanCodes](https://youtu.be/txRTzljmV0Q)

## References:

1. [python.org docs - Chapter 9: Classes](https://docs.python.org/3/tutorial/classes.html)

2. [Quora](https://www.quora.com/Besides-object-oriented-programming-what-other-types-are-there-and-what-are-their-uses)

3. [FreeCodeCamp](https://www.freecodecamp.org/news/an-introduction-to-programming-paradigms/)

4. [RealPython.com - Python Classes: The Power of Object-Oriented Programming](https://realpython.com/python-classes/#getting-started-with-python-classes)

5. [geeksforgeeks.org - self in Python class](https://www.geeksforgeeks.org/self-in-python-class/)

6. [Youtube - Corey Schafer - Python OOP Tutorial](https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc)

## INTRODUCTION

### Programming paradigms

<span style="color:grey">

"Programming paradigms are different ways or styles in which a given program or programming language can be organized."

</span>
by FreeCodeCamp

Classification of programming langauges into paradigms is intended to guide users on best languages to use for certain scenarios and types of problems. It is worthy to note that a programming language can be described using several paradigms, and that the **paradigms are NOT mutually exclusive**, even though some have been built to satisfy requirements of a specific paradigm.

The paradigms are described below:

#### 1. Imperative:

consists of sets of detailed instructions that are given to the computer to execute in a given order. Imperative programming focuses on describing how a program operates, step by step, from top to bottom.

Illustration: procedure for baking a cake
```
1- Pour flour in a bowl
2- Pour a couple eggs in the same bowl
3- Pour some milk in the same bowl
4- Mix the ingredients
5- Pour the mix in a mold
6- Cook for 35 minutes
7- Let chill
```

#### 2. Procedural: 

Follows a sequence of statements or commands in order to achieve a desired output. Each series of steps is called a procedure or subroutine (functions).

Example: C and C++, Java, Pascal, BASIC

Illustration: procedure for baking a cake
```
function pourIngredients() {
    - Pour flour in a bowl
    - Pour a couple eggs in the same bowl
    - Pour some milk in the same bowl
}

function mixAndTransferToMold() {
    - Mix the ingredients
    - Pour the mix in a mold
}

function cookAndLetChill() {
    - Cook for 35 minutes
    - Let chill
}

pourIngredients()
mixAndTransferToMold()
cookAndLetChill()
```

#### 3. Functional: 

Focus on the output of mathematical functions and evaluations. Each function–a reusable module of code–performs a specific task and returns a result. Functions can be assigned to variables, passed as arguments, and returned from other functions.

Examples: Scala, Erlang, Haskell, Elixir, F#

Illustration: 

Imperative programming
```
nums = [1,4,3,6,7,8,9,2]
result = [] # External variable
num_length = len(nums)

for i in num_length:
    if nums[i] > 5:
        result.append(i)

print(result) // Output: [ 6, 7, 8, 9 ]
```
Functional programming
```
nums = [1,4,3,6,7,8,9,2]

def filterNums():
    result = [] // Internal variable
    for i in num_length:
        if nums[i] > 5:
            result.append(i)
    return result

print(result) // Output: [ 6, 7, 8, 9 ]
```
When external variables are used to store a function's result, this can be considered as being a side effect. Functional programming ensures that a function does not modify any variable outside of its scope.

#### 4. Declarative: 

Characterised by statements which declare precisely the changes that need to be made. It is all about hiding away complexity and bringing programming languages closer to human language and thinking.

`filter`, `map`, `reduce` and `sort` functions are good examples of declarative code.

Examples: RDBMS eg. SQL

#### 5. Object-Oriented: 

Treats a program as a group of objects composed of data and program elements, known as attributes and methods. Objects can be reused within a program or in other programs. In OOP, classes are heavily used, and are used as blueprint (parent) and their properties are inherited by instances (child).

Examples: Java, Python, PHP, C++, Ruby

Illustration:
```
// Create the two classes corresponding to each entity
class Cook {
	constructor constructor (name) {
        this.name = name
    }

    mixAndBake() {
        - Mix the ingredients
    	- Pour the mix in a mold
        - Cook for 35 minutes
    }
}

class AssistantCook {
    constructor (name) {
        this.name = name
    }

    pourIngredients() {
        - Pour flour in a bowl
        - Pour a couple eggs in the same bowl
        - Pour some milk in the same bowl
    }
    
    chillTheCake() {
    	- Let chill
    }
}

// Instantiate an object from each class
const Frank = new Cook('Frank')
const Anthony = new AssistantCook('Anthony')

// Call the corresponding methods from each instance
Anthony.pourIngredients()
Frank.mixAndBake()
Anthony.chillTheCake()
```

### Classes and Functions: When to Use Each
Functions
* Easier to test with unit test
* More readable code

Classes
* Modeling real-world concepts eg. real-estate systems with buyers, sellers and houses classes and instances

<img src="./class_function.png" width="550">

When using classes, avoid very deep inheritances.

Key to success: Experiment with Functions, Classes and combinations of both.

## PYTHON CLASS TERMINOLOGIES

While handling classes, we will come across several concepts and terminologies. These are as follows:

<img src="./Classes example.png">

* Attributes: variables defined inside a class with the purpose of storing all the required data for the class to work. Refer to the properties or data associated with a specific object of a given class.
* Methods: functions defined in the class. Refer to the different behaviors that objects will show
* Instance: a class object that has been derived from the class. Each instance will access all attributes and methods of the Parent class and can edit them without effecting changes in the parent class. New attributes and methods can also be introduced in the instances, which the parent class cannot access.

In [4]:
import pandas as pd
df=pd.DataFrame()

In [5]:
df_2 = pd.read_csv("./energydata.csv")

FileNotFoundError: [Errno 2] No such file or directory: './energydata.csv'

In [7]:
df_3 = pd.read_csv("./train.csv")

FileNotFoundError: [Errno 2] No such file or directory: './train.csv'

In [ ]:
df_2.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [ ]:
df_3.describe()

,Activity,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
count,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,...,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000
mean,0.542255,0.076948,0.592436,0.068142,0.038990,0.212112,0.686653,0.274713,0.455133,0.749517,...,0.026926,0.014663,0.013863,0.021861,0.015196,0.016796,0.012263,0.011730,0.020261,0.011197
std,0.498278,0.079989,0.105860,0.078414,0.115885,0.102592,0.078702,0.090017,0.162731,0.071702,...,0.161889,0.120215,0.116938,0.146249,0.122348,0.128522,0.110074,0.107683,0.140911,0.105236
min,0.000000,0.000000,0.282128,0.000000,0.000000,0.002630,0.137873,0.006130,0.000000,0.275590,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.033300,0.517811,0.000000,0.000000,0.138118,0.625627,0.207374,0.378062,0.707339,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.066700,0.585989,0.050000,0.000000,0.190926,0.674037,0.277845,0.499942,0.738961,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.100000,0.668395,0.100000,0.000000,0.261726,0.740663,0.335816,0.569962,0.788177,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,0.964381,0.950000,1.000000,1.000000,0.994735,0.790831,0.989870,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.shape

## CLASSES AND INSTANCES

### Creating Classes

Defining a class will require at minimum:
* `class` keyword
* '`:`'
* `def --init--()`: object initializer. It defines and sets the initial values for attributes
* `self` parameter: represents the instance of the class that is currently being used. Note that it is not a keyword

`self` has the following characteristics:
* pointer to current object
* first argument to be passed in Constructor and Instance Method
* a convention and not a Python keyword

class attributes are accessed by class methods by prefixing `self.` to the attribute names.

Accessing class attributes: obj.attribute_name

Accessing class methods: obj.method_name()

In [8]:
# Syntax

class ClassName: # convention of naming classes - First Upper case letter
    def __init__(self, *args, **kwargs): # attributes definition and initialization
        pass
    # other class methods and attributes

In [9]:
# Defining a Class that will model Employee system
# Syntax


class Employee:
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def salaryIncrease(self) -> str:
        if self.salary > 50_000:
            return True
        else:
            print("No Increase")

### Creating Instances

In [10]:
Bdev_1 = Employee('Rogers','Mugambi',50000, 'V') # instantiation
Bdev_2 = Employee('Caroline','Ayieko',50000, 'V') # instantiation
Bdev_3 = Employee('Kelvin','Wanjiku',50000, 'V') # instantiation

In [11]:
# Accessing class methods

Employee.email() # instance needs to be passed as an argument

TypeError: Employee.email() missing 1 required positional argument: 'self'

In [12]:
# Accessing class methods

#Method 1
Employee.email(Bdev_1)
Employee.email(Bdev_2)
Employee.email(Bdev_3)

Rogers.Mugambi@pye.com
Caroline.Ayieko@pye.com
Kelvin.Wanjiku@pye.com

In [13]:
Employee.salaryIncrease(Bdev_1)

No Increase

In [14]:
# Accessing class methods

#Method 2
Bdev_1.email()
Bdev_2.email()
Bdev_3.email()

Rogers.Mugambi@pye.com
Caroline.Ayieko@pye.com
Kelvin.Wanjiku@pye.com

In [15]:
Bdev_1.salaryIncrease() # instance mthod

No Increase

Above error resulted from not prefixing `self` in the definition of `salaryIncrease` method.

In [16]:
Bdev_1.firstName

'Rogers'

## CLASS VARIABLES VS INSTANCE VARIABLES

Class Variables: Variables created within the definition of a class that can be shared by all instances of a class

Instance Variables: Variable that can be unique for each instance.

In [22]:
class Employee_:
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def apply_raise(self) -> int:
        self.salary = int(self.salary * 1.4) # hardcoding a raise-amount rate at class level

In [23]:
Bdev_1 = Employee_('Rogers','Mugambi',50000, 'V') # instantiation
print(Bdev_1.salary)
Bdev_1.apply_raise()
print(Bdev_1.salary)

50000
70000

Therefore, the salary has been raised by 1.4

In [1]:
class Employee_1:
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def apply_raise(self):
        self.salary = int(self.salary * self.raise_amount) # raise_amount has not been initialised, but will not raise an error

In [2]:
Bdev_1 = Employee_1('Rogers','Mugambi',50000, 'V') # instantiation
Bdev_2 = Employee_1('Kelvin','Macharia',50000, 'V') # instantiation
Bdev_3 = Employee_1('Carol','Kemunto',50000, 'V') # instantiation
print(Bdev_1.__dict__)

{'firstName': 'Rogers', 'lastName': 'Mugambi', 'salary': 50000, 'level': 'V', 'userEmail': 'Rogers.Mugambi@pye.com'}

In [3]:
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

AttributeError: 'Employee_1' object has no attribute 'raise_amount'

We can see the raise_amount attribute is not within the definition of the instance, and,

In [4]:
print(Employee_1.__dict__)

{'__module__': '__main__', '__init__': <function Employee_1.__init__ at 0x00000190FDD1B740>, 'email': <function Employee_1.email at 0x00000190FDD1BF60>, 'apply_raise': <function Employee_1.apply_raise at 0x00000190FDD88040>, '__dict__': <attribute '__dict__' of 'Employee_1' objects>, '__weakref__': <attribute '__weakref__' of 'Employee_1' objects>, '__doc__': None}

before initialisation of the `raise_amount` variable, it is not included in the class dictionary.

In [5]:
Employee_1.raise_amount = 1.5

print(Employee_1.__dict__)

{'__module__': '__main__', '__init__': <function Employee_1.__init__ at 0x00000190FDD1B740>, 'email': <function Employee_1.email at 0x00000190FDD1BF60>, 'apply_raise': <function Employee_1.apply_raise at 0x00000190FDD88040>, '__dict__': <attribute '__dict__' of 'Employee_1' objects>, '__weakref__': <attribute '__weakref__' of 'Employee_1' objects>, '__doc__': None, 'raise_amount': 1.5}

In [6]:
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.5
1.5
1.5

In [1]:
class Employee_1:
    
    raise_amount = 1.0 # implementing soft-coding, instead of  hardcoding the raise-amount value
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def apply_raise(self):
        self.salary = int(self.salary * self.raise_amount)

In [2]:
Bdev_1 = Employee_1('Rogers','Mugambi',50000, 'V') # instantiation
Bdev_2 = Employee_1('Kelvin','Macharia',50000, 'V') # instantiation
Bdev_3 = Employee_1('Carol','Kemunto',50000, 'V') # instantiation
print(Bdev_1.__dict__)

{'firstName': 'Rogers', 'lastName': 'Mugambi', 'salary': 50000, 'level': 'V', 'userEmail': 'Rogers.Mugambi@pye.com'}

As the raise_amount value was not initialised within the __init__ method of the class, it does not appear within the instance dict.

In [3]:
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.0
1.0
1.0

In [4]:
print(Employee_1.__dict__)

{'__module__': '__main__', 'raise_amount': 1.0, '__init__': <function Employee_1.__init__ at 0x000002F4EEBDB740>, 'email': <function Employee_1.email at 0x000002F4EEBDBF60>, 'apply_raise': <function Employee_1.apply_raise at 0x000002F4EEC48040>, '__dict__': <attribute '__dict__' of 'Employee_1' objects>, '__weakref__': <attribute '__weakref__' of 'Employee_1' objects>, '__doc__': None}

In [5]:
print(Employee_1.raise_amount)

1.0

After initialization, the `raise_amount` is included in the class dict. And all instances have accessed the same value of raise_amount.Note that we have initiaised the raise_amount variable at the class level. 

Now, what if we initialise at the instance level? Say we want to increase the rate for just one employee instead for the whole group.

In [ ]:
Bdev_1.raise_amount = 1.7

In [7]:
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.7
1.0
1.0

We see then that the initialisation of a class variable at the instance level does not change the varable as the class level. As such, we can have each instance having it own value of a class variable, and the class variable having a completely different value.

In [8]:
Bdev_2.raise_amount = 1.1
Bdev_3.raise_amount = 1.3

In [9]:
print(Employee_1.raise_amount)
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.0
1.7
1.1
1.3

As such, any other new instance created from the `Employee` class will inherit the "default" value of raise_amount.:

In [10]:
Bdev_4 = Employee_1('Lilian','Motongori',50000, 'V') # instantiation
print(Bdev_4.raise_amount)

1.0

Now, we want to know the number of employees instances that have been created:

In [1]:
class Employee_2:
    
    num_of_emps = 0
    raise_amount = 1.0
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
        Employee_2.num_of_emps += 1 # this counts how many times the Employee class has been instantiated
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def apply_raise(self):
        self.salary = int(self.salary * self.raise_amount)

NOTE: Research on how `cls` can be used to represent the class name within the class definition code.

## CLASS METHODS VERSUS STATIC METHODS

Instance methods automatically take the instanc as the first argument `self`.

A class method, on the other hand, is created by adding a `@classmethod` decorator.

While instance methods and class methods pass the instance (`self`) and class (`cls`) automatically as the first argument, respectively, static methods do not pass anything automatically.

Static methods are used where an action is related to the class logically but is not dependent on any specific instance or class variable. Static methods are created by adding `@staticmethod` decorator before a regular method.

### Instance methods

In [ ]:
class Employee:
    
    raise_amount = 1.0 # implementing soft-coding, instead of  hardcoding the raise-amount value
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    def apply_raise(self): # regular method
        self.salary = int(self.salary * self.raise_amount)

### Class methods

In [1]:

class Employee:
    
    raise_amount = 1.0 # implementing soft-coding, instead of  hardcoding the raise-amount value
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    
    def apply_raise(self): # regular method
        self.salary = int(self.salary * self.raise_amount)
    
    @classmethod # adding this decorator to convert regular method to class method
    def set_raise_rate(cls, rate): # cls used instead of self to rep. the class
        cls.raise_amount = rate
        
    def __str__(self):
        return self.firstName + " " + self.lastName

In [2]:
Bdev_1 = Employee('Rogers','Mugambi',50000, 'V') # instantiation
Bdev_2 = Employee('Kelvin','Macharia',50000, 'V') # instantiation
Bdev_3 = Employee('Carol','Kemunto',50000, 'V') # instantiation

In [3]:
print(Bdev_1)

Rogers Mugambi

Class methods can be used to update static class attributes.

Let us check the rate of salary increase:

In [4]:
print(Employee.raise_amount)
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.0
1.0
1.0
1.0

The `raise_amount` has a value of `1.0` at the class and at all the instance levels, and is the default value, as defined within the class definition.

Within the class definition, we created a method that can be used to set a new rate of increase. 

As a class method, any new value passed to this method updates the value stored by the attribute `raise_amount` at the class level.

The update then gets propagated to all the instances. This is shown below:

In [5]:
Employee.set_raise_rate(1.05) # setting new default rate

In [6]:
print(Employee.raise_amount)
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.05
1.05
1.05
1.05

This works. 

Now, what if we had adjusted the value of `raise_amount` for one of the developers prior to updating of the default value stored in the class?

In [7]:
Bdev_3.raise_amount = 1.20

In [8]:
print(Employee.raise_amount)
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

1.05
1.05
1.05
1.2

In [9]:
Employee.set_raise_rate(2.0) # setting new default rate

In [10]:
print(Employee.raise_amount)
print(Bdev_1.raise_amount)
print(Bdev_2.raise_amount)
print(Bdev_3.raise_amount)

2.0
2.0
2.0
1.2

We can see that adjusting "default" value of the `raise_amount` does not over-write values at the instance level if they have been changed from the default values.

NOTE: Class methods can be accessed through instances, though this approach seems to lack meaningful utility.

### Class Methods as Constructors

Convention: names begin with `from_`. eg. from_string, and are terminated by a `return` statement.

In [1]:
# Example of Constructor that parses a string and creates an instance
# from a comma-delimited text containing  employee details

class Employee:
    
    raise_amount = 1.0 # implementing soft-coding, instead of  hardcoding the raise-amount value
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    @classmethod # adding this decorator to convert regular method to class method
    def from_string(cls, string): # cls used instead of self to rep. the class
        first, last, salary, level =  string.split(',')
        return cls(first, last, salary, level) # creates and returns an instance. 
                                                # Similar to Employee(first, last, salary, level)

In [7]:
# sample input

string = "Rogers,Mugambi,50000,'V'"
Bdev_4 = Employee.from_string(string)
print(Bdev_4.salary)

50000

Explore more on usecases for class methods.

### Static Methods

In [1]:
class Employee:
    
    raise_amount = 1.0 # implementing soft-coding, instead of  hardcoding the raise-amount value
    
    # defining class variables
    def __init__(self, firstName: str, lastName: str, salary: int, level: str):
        self.firstName = firstName
        self.lastName = lastName
        self.salary = salary
        self.level = level
        self.userEmail = self.firstName+'.'+self.lastName+'@pye.com' 
        
    def email(self) -> str:
        emailAddress = self.firstName+'.'+self.lastName+'@pye.com'
        return print(emailAddress)
    
    @staticmethod
    def is_workday(day): # DO NOT pass either 'self' nor 'cls'
        if day.weekday() == 5 or day.weekday() == 6:
            return False
        return True

In [4]:
import datetime
my_date = datetime.date(2024,4,7)

print(Employee.is_workday(my_date))

False

If it becomes evident that no class variable or method is to be used within a method, then the method needs to be a static method.

## INHERITANCE, POLYMORPHISM & ABSTRACTION

### Inheritance

Allows one class to acquire the properties (attributes) and behaviors (methods) of another class. 

The class being inherited from is called the parent class or superclass.

The class that inherits is called the child class or subclass.

In [11]:
class Animal:  # Parent class
    def __init__(self, name):
        self.name = name
    def printName(self):
        print(self.name)

class Dog(Animal):  # Child class
    def bark(self):
        return "Woof!"

dog1 = Dog("Alfa")
dog1.printName()
print(dog1.bark())

Alfa
Woof!

Suppose we have a general Vehicle class that defines properties common to all vehicles, such as make, model, and year. Now, we want to create a Car class that has all the properties of Vehicle, but also some properties specific to cars, like number_of_doors.

In [16]:
class Vehicle: # parent class
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

# within vehicles, we have several categories: cars, SUVs, Trucks, Motorcycles, Lorry

# class Car(Vehicle): # child class
#     def __init__(self, number_of_doors):
#         self.number_of_doors = number_of_doors
        
class Car(Vehicle): # child class
    def __init__(self, make, model, year, number_of_doors):
        super().__init__(make, model, year)
        self.number_of_doors = number_of_doors

car1 = Car("Toyota",'Corolla','2024',4)

class Lorry(Vehicle): # child class
    def __init__(self,make, model, year, axles):
        super().__init__(make, model, year)
        self.axles = axles
        
lorry1 = Lorry('Benz','Actros550','2024','10')

In this example, Car is a subclass of Vehicle and inherits its properties and methods. The super() function is used to call the __init__() method of the Vehicle superclass, which allows us to use its properties in the Car subclass.

### Subclasses

A subclass is a class that inherits from one or more classes. 

Python supports multiple inheritance, which means a subclass can have more than one superclass and inherit features from all superclasses.

Let’s extend our vehicle example. Suppose we want to create a Convertible class that inherits properties from both the Car and a ConvertibleFeatures class:

In [4]:
class Vehicle: # parent class - Level 1
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

class Car(Vehicle): # child class - Level 2
    def __init__(self, make, model, year, number_of_doors):
        super().__init__(make, model, year)
        self.number_of_doors = number_of_doors

class ConvertibleFeatures: # parent class - Level 1
    def __init__(self, roof_type):
        self.roof_type = roof_type

class Convertible(Car, ConvertibleFeatures): # Inheritance from more than one class
    def __init__(self, make, model, year, number_of_doors, roof_type):
        Car.__init__(self, make, model, year, number_of_doors)
        ConvertibleFeatures.__init__(self, roof_type)

In this example, Convertible is a subclass that inherits from both the Car and ConvertibleFeatures classes. It uses the __init__() methods of both superclasses to inherit their properties.

While inheritance and subclasses can make our code more modular and easier to maintain, they can also make it more complex.

It is important to ensure the features with care (judiciously) and keep code as simple as possible.

#### Homework:

In our project:

Classes:
- Products: Name, Category, price, description
- Sales: Subclass of Products

### Polymorphism

Polymorphism allows us to use a single interface with different underlying forms. 

Polymorphism allows us to define methods in the child class with the same name as defined in their parent class.

In [5]:
class Animal:  # Parent class
    def __init__(self, name):
        self.name = name

class Dog(Animal):  # Child class
    def bark(self):
        return "Woof!"

class Cat(Animal):  # Another child class of Animal
    def sound(self):
        return "Meow!"

# Using Polymorphism
def animal_sound(animal):
    print(animal.sound())

cat = Cat("Tom")
dog = Dog("Spike")

animal_sound(cat)  # Outputs: Meow!
animal_sound(dog)  # Outputs: Woof!

Meow!
Woof!

In this example, both Cat and Dog classes have a method named sound, but the implementations are different. This is polymorphism.

### Abstraction

Abstraction allows us to hide the internal implementation details and show only the functionality to the users. 

In Python, we achieve abstraction using abstract classes and interfaces.

In [6]:
from abc import ABC, abstractmethod

class AbstractAnimal(ABC):  # Abstract Class
    @abstractmethod
    def sound(self):
        pass

class Dog(AbstractAnimal):  # Child class
    def sound(self):
        return "Woof!"

In this example, AbstractAnimal is an abstract class that declares the sound method but doesn’t provide any implementation. The Dog class provides the implementation for the sound method.

### Use Cases

#### Inheritance

Promote code reuse and make code easier to maintain.

Example: 

consider a software company that has a basic Employee class. This class has attributes like name, id, salary, etc., and methods like get_salary(), get_id(), etc. Now, the company wants to create Manager and Engineer classes. Instead of rewriting all the code for these new classes, they can simply inherit from the Employee class and add or override the methods they need. This saves time and helps keep the code DRY (Don’t Repeat Yourself).

#### Polymorphism

Make systems more modular and extensible.

Example: 

consider a drawing application that supports shapes like Circle, Rectangle, and Triangle. Each of these shapes has a draw() method. When the user selects a shape and drags the mouse, the application doesn’t need to know what kind of shape it is - it just calls the draw() method. This is polymorphism. If you want to add a new shape to the application, you just create a new class for that shape and implement the draw() method. The existing code doesn’t need to change, which makes the system easy to extend.

#### Abstraction

Used to hide complexity of the system and expose only the necessary details.

Example: 

consider a car. A car is a complex machine with many parts like an engine, gearbox, etc. But when you drive a car, you don’t need to know how all these parts work - you only need to know how to use the steering wheel, accelerator, and brakes. This is abstraction. In programming, we achieve abstraction using interfaces and abstract classes. They allow us to hide the internal workings of a class and show only the methods and properties that the user needs to know about.

Example 2: 

let’s say you want to use the Python statistics module, which is a built-in module in Python. This means that Python already comes with the module in its library. You don’t need to import it with PIP2. To use this module, you just need to know how to call its functions. You don’t need to understand how these functions are implemented. This is an example of abstraction2.